### ISSUE TITLE
An easier way of deobfuscation "fuckbox"

### ISSUE THREAD

**Issue by KosBeg** [niklasb/34c3ctf-sols#1]
Hi!)
After reading write-up "fuckbox", I just could not help not fix this whole thrash.
Deobfuscation of the script is done in a few copy-past:
1) download the script http://35.198.119.82/fuckbox/payload.js
2) delete the last two characters - ()
3) paste this text in the console of the Chrome (F12 -> console) or Microsoft Edge(but not firefox) and press ENTER
4) beautify that code at jsbeautifier.org
and we have
```
let eq = (a, b) => {
  for (let i = 0; i < 16; ++i)
    if (a[i] != b[i]) return false;
  return true;
};

let doit = () => {
  let key = aesjs.utils.utf8.toBytes($('#password').val());
  if (key.length !== 16) return false;
  for (let i = 0; i < 16; ++i)
    if (key[i] < 97 || key[i] > 122) return false;
  let aes = new aesjs.AES(key);
  let plain = aesjs.utils.utf8.toBytes("hitharyoucanAES?");
  let cipher = [52, 7, 86, 202, 209, 142, 18, 112, 135, 39, 220, 225, 83, 85, 254, 92];
  if (!eq(aes.encrypt(plain), cipher)) return false;
  let iv = [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36];
  aes = new aesjs.ModeOfOperation.cbc(iv, iv);
  plain = new Uint8Array(64);
  for (let i = 0; i < 64; i += 16) plain.set(key, i);
  cipher = aes.encrypt(plain);
  let xor = [28, 41, 44, 126, 250, 34, 40, 104, 231, 247, 67, 229, 132, 68, 163, 165, 125, 34, 128, 94, 106, 118, 140, 7, 37, 17, 115, 14, 165, 216, 211, 208, 204, 233, 165, 29, 144, 234, 133, 91, 26, 24, 23, 27, 224, 154, 89, 14, 74, 167, 73, 52, 241, 253, 214, 4, 241, 249, 46, 35, 204, 192, 144, 147];
  let flag = '';
  for (let i = 0; i < 64; ++i) flag += String.fromCharCode(xor[i] ^ cipher[i]);
  alert("The flag is: " + flag);
  return true;
};

check = () => {
  if (!doit()) alert("Wrong password!");
};
```
I apologize if I misunderstood something, because the part with the DFA attack I absolutely did not understood

**Comment by niklasb** [comment]
Haha you cannot solve it if you do this. It's a trap.

**Comment by niklasb** [comment]
Happy fucking 2018!

**Comment by KosBeg** [comment]
Ok, thanks, I'll try to understand)

**Comment by niklasb** [comment]
The trick as that one of the lines is dynamically generated:

```
let cipher = [52, 7, 86, 202, 209, 142, 18, 112, 135, 39, 220, 225, 83, 85, 254, 92];
```

It is actually computed via an whitebox AES encryption implemented in a Javascript-subset of 8 characters (not quite JSFuck). You have to find the AES implementation in the obfuscated code and extract the key from it.
